server:
  port: ${SERVER_PORT:9090}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:9999}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.5
    gateway:
      routes:
        - id: user-route
          uri: ${USER_SERVICE_URI:http://localhost:9091}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/${api.version}

        - id: user-management-route
          uri: ${USER_SERVICE_URI:http://localhost:9091}
          predicates:
            - Path=/management/users/**
          filters:
            - PrefixPath=/api/${api.version}

        - id: order-route
          uri: ${ORDER_SERVICE_URI:http://localhost:9092}
          predicates:
            - Path=/orders/**
          filters:
            - PrefixPath=/api/${api.version}
            - AuthFilter

        - id: order-management-route
          uri: ${ORDER_SERVICE_URI:http://localhost:9092}
          predicates:
            - Path=/management/orders/**
          filters:
            - PrefixPath=/api/${api.version}
            - AuthFilter

        - id: product-route
          uri: ${PRODUCT_SERVICE_URI:http://localhost:9093}
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api/${api.version}
            - AuthFilter

        - id: product-management-route
          uri: ${PRODUCT_SERVICE_URI:http://localhost:9093}
          predicates:
            - Path=/management/products/**
          filters:
            - PrefixPath=/api/${api.version}
            - AuthFilter

app:
  user-url: ${USER_SERVICE_URI:http://localhost:9091}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    healths:
      show-details: always
    gateway:
      enabled: true
